# Find the Difference

''' You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.'''

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        
        list_s = [s[i] for i in range(len(s))]  
        list_t = [t[i] for i in range(len(t))]  
        for letter in list_s:  
            list_t.remove(letter)  
        return(list_t[0])  

sol = Solution()
s = "abcd"
t = "abcde"
result = sol.findTheDifference(s, t)
print("Result:", result)